### ISSUE TITLE
systemd service doesn't find executable

### ISSUE THREAD

**Issue by suyd** [cdown/zcfan#14]
after installing with sudo make install on ubuntu, the binary installs into /usr/local/bin but the service path is on /usr/bin/zcfan

fixed it changing the location of the executable to /usr/local/bin/zcfan

please tell me if you need more info

**Comment by cdown** [comment]
Hmm, yes. I suppose we should templatise the systemd file.

**Comment by ilmanzo** [comment]
Since it's a program typically used only from root (or systemd), I'd propose `/usr/sbin` as executable path location

**Comment by cdown** [comment]
That's probably true, I'm on a /usr merged distribution so don't think about this much. I'd rather avoid having to use some crappy templating system just for this, probably this can just be done through the makefile.
