### ISSUE TITLE
zcfan causes freeze on ThinkPad T16 Gen 1 AMD

### ISSUE THREAD

**Issue by joaquinvacas** [cdown/zcfan#15]
Hi!

I know it shouldn't happen at all, not sure if it's directly related to zcfan but thinkpad_acpi.

Anyhow, it manages to crash my system when I enable zcfan.

Sometimes it just happens at the first boot, sometimes happens 4h after using it.

Not sure if laptop it's too much new and it doesn't have a good support as other ThinkPads do.

This works more as a warning for those users loosing their minds on why their systems keep freezing than a real issue.

**Comment by cdown** [comment]
Hey there!

Wow, that's... bizarre. It almost certainly must be a bug in thinkpad_acpi. Does the same thing happen with thinkfan?

**Comment by cdown** [comment]
I'm going to close this as this should be tracked as part of thinkpad_acpi. Thanks for the report, though.
