### ISSUE TITLE
Can be used together with auto-cpufreq

### ISSUE THREAD

**Issue by CRAG666** [cdown/zcfan#16]
I currently use auto-cpufreq to manage cpu power and frequency but I was wondering if it is possible to use it together with this awesome package, by the way I use a thinkpad p53 so I don't know if I can use this package anywhere. Thanks

**Comment by cdown** [comment]
There shouldn't be any conflict, although they may compete in terms of attempting hysteresis. Is there some poor behaviour you're seeing?

**Comment by CRAG666** [comment]
No, it was just a question, I've had it for several days, I haven't noticed any problems but it doesn't hurt to ask

**Comment by cdown** [comment]
Sure thing, I'll close then.

**Comment by CRAG666** [comment]
@cdown  Is there a problem using thermald and zcfan?
