### ISSUE TITLE
zcfan on Fedora Silverblue/Kinoite?

### ISSUE THREAD

**Issue by Pyntux** [cdown/zcfan#18]
Just a question, does zcfan works on immutable Fedora? Some recommendation?

P.S. 
/etc is writable!

**Comment by cdown** [comment]
If /sys and /proc have normal permissions, then yes.

**Comment by Pyntux** [comment]
No, /sys and /proc are not writable.... But, if I layer package on system image, does that have any differences?

**Comment by asoliadlad** [comment]
I can confirm this zcfan works on Silverblue 40.

**Comment by Pyntux** [comment]
Yes... : ) You need first to do:

rpm-ostree kargs --append=thinkpad_acpi.fan_control=1

than just enable zcfan.service and that is it.
