### ISSUE TITLE
Stop program on suspend and resume on wakeup ?

### ISSUE THREAD

**Issue by ilmanzo** [cdown/zcfan#21]
A similar project, [thinkfan](https://github.com/vmatare/thinkfan) , provides systemd units that kicks in when laptop changes to [suspend and wake-up](https://github.com/vmatare/thinkfan/tree/master/rcscripts/systemd) states. Could be useful to have also here ?

**Comment by cdown** [comment]
Any idea why thinkfan does this? At least on my T14s, the fan state appears to be in the same state zcfan left it on wakeup.

**Comment by cdown** [comment]
Looking at the commit ([2b8d04fb51c904213ba6739e60f20db37d23a3a0](https://github.com/vmatare/thinkfan/commit/2b8d04fb51c904213ba6739e60f20db37d23a3a0)), the rationale provided is:

> Allows us to perform the hwmon PWM re-init that is necessary after wakeup from suspend. On other init systems, the distro-specific package maintainer still needs to deal with this.

So it semes my guess is probably right for some models? Are those models still common?

**Comment by cdown** [comment]
Can you please test 69b0a4af0a679aed8377188512ffff86ba357873 on an affected system? Since my T14s is unaffected, I'm not really able to test.

**Comment by ilmanzo** [comment]
I've tested `zcfan` on a P15Gen2, but wasn't able to reproduce the issue with suspend/resume, while with `thinkfan` sometimes the system could not enter sleep mode. Also I'm not sure if detecting a 'jump' in time plays well with time synchronization, so no big deal for now.

**Comment by cdown** [comment]
Fascinating, well at least I'm glad zcfan doesn't suffer from this :-) I'll close for now then. Thanks!
