### ISSUE TITLE
Why is the watchdog operated with 120 second timeout?

### ISSUE THREAD

**Issue by errge** [cdown/zcfan#22]
This is my first look at this project, so I might be completely in the wrong here, but I don't understand why does the code initializes the watchdog to 2 minutes (120 sec) instead of something like 10 seconds.  The watchdog is pinged every 2-3 seconds, so the kernel scheduler or something has to go really wrong for the watchdog to fire at let's say 10 second.

2 minutes seems to be a long time with modern hardware, and if zcfan stops running (operator error, crash, systemd fail, whatever), then in 2 minutes a machine can get really hot if something is consuming a lot of CPU at the same time.

I know this is a constant in the code, and I can easily change it for myself, but for people who are using this from a distribution (e.g. Debian), it's not so easy to do this, as the option is not configurable without rebuild.  Could we make this changeable from config/envvar, or change the builtin default constant to some drastically smaller value (e.g. 5 or 10)?

**Comment by cdown** [comment]
It's operated with an infrequent watchdog timeout because it reduces the number of wakeups.

> The watchdog is pinged every 2-3 seconds, so the kernel scheduler or something has to go really wrong for the watchdog to fire at let's say 10 second.

That's not correct, we don't write again unless the watchdog timer will elapse soon or the speed is changing. See `set_fan_level`.

> Could we make this changeable from config/envvar, or change the builtin default constant to some drastically smaller value (e.g. 5 or 10)?

Sure, nobody has asked for it until now. Feel free to add a `watchdog_secs` directive.

**Comment by errge** [comment]
Thank you for the information regarding the fan_level frequency, and for the guidelines on how to make this configurable.

Please find the attached PR on my first try to adding this new directive.
