### ISSUE TITLE
Support full-speed and disengaged levels

### ISSUE THREAD

**Issue by norpol** [cdown/zcfan#26]
It would be great if the fan could go up to full-speed and for limited time even disengaged.

**Comment by cdown** [comment]
We already go to disengaged when below low_temp, and to max speed at max_temp. Could you please explain further if you meant something else?

**Comment by norpol** [comment]
From [kernel.org](https://www.kernel.org/doc/Documentation/laptops/thinkpad-acpi.txt):

> Where <level> is an integer from 0 to 7, or one of the words "auto" or
"full-speed" (without the quotes).  Not all ThinkPads support the "auto"
and "full-speed" levels.  The driver accepts "disengaged" as an alias for
"full-speed", and reports it as "disengaged" for backwards
compatibility.

Disengaged/full-speed will run at a faster speed then Level 7. I thought there was a difference between disengaged and full-speed, but that appears to have been just for backwards compatibility. Disengaged doesn't mean "no fan" but "no rpm control". 

Level 7 are just ~5250 rpm on the Thinkpad X1C, Disengaged are almost 7000rpm.

**Comment by cdown** [comment]
So it looks like there needs to be a test for `full-speed` support prior to setting it. I'm not against it, but I need to check how this failure looks like (since `full-speed` works on my T14s).

**Comment by norpol** [comment]
Seems it reports whether full-speed is supported: https://github.com/torvalds/linux/blob/ab0a97cffa0bb3b529ca08b0caea772ddb3e0b5c/drivers/platform/x86/thinkpad_acpi.c#L9047-L9059

The error if full-speed isn't supported should be the same as if you pass any other invalid value if I'm not mistaken.

https://github.com/torvalds/linux/blob/ab0a97cffa0bb3b529ca08b0caea772ddb3e0b5c/drivers/platform/x86/thinkpad_acpi.c#L8262-L8265

**Comment by cdown** [comment]
Well, annoyingly it doesn't propagate it to userspace and just logs:

```c
static int fan_write_cmd_level(const char *cmd, int *rc)
{
	int level;

	if (strstarts(cmd, "level auto"))
		level = TP_EC_FAN_AUTO;
	else if (strstarts(cmd, "level disengaged") || strstarts(cmd, "level full-speed"))
		level = TP_EC_FAN_FULLSPEED;
	else if (sscanf(cmd, "level %d", &level) != 1)
		return 0;

	*rc = fan_set_level_safe(level);
	if (*rc == -ENXIO)
		pr_err("level command accepted for unsupported access mode %d\n",
		       fan_control_access_mode);
	else if (!*rc)
		tpacpi_disclose_usertask("procfs fan",
			"set level to %d\n", level);

	return 1;
}
```

It seems we can look at `commands`, though.

**Comment by norpol** [comment]
Hm, looking at `strace` when I'm running `echo 'level 10' | sudo strace -f -s 1024 tee /proc/acpi/ibm/fan` shows to me that the error propagates, at least for my example when setting a value that isn't supported. But the code I linked before is also doing `EINVAL` for when `full-speed` isn't supported.


This is how it looks in strace

`write(3, "level 10\n", 9)               = -1 EINVAL (Invalid argument)`

**Comment by norpol** [comment]
Thank you for the fast implementation, just build and verified it's using the highest level now.
Have a good weekend.

**Comment by cdown** [comment]
you too!
