### ISSUE TITLE
Control of fan levels

### ISSUE THREAD

**Issue by avylove** [cdown/zcfan#3]
Great project! I installed the RPM and it pretty much worked out of the box.

The only issue I'm running into is the low speed on my machine isn't particularly low, so I'm wondering if you can add a configuration option to set what the levels correspond to. That, or support specifying levels as integers instead of by label.

To give some context, here is what I'm observing on my system:

| Level | RPMS |
| ------- | --------- |
| 0  | 0  |
| 1  | 2820  |
| 2  | 3360  |
| 3  | 3670  |
| 4  | 3670  |
| 5  | 3670  |
| 6  | 4020  |
| 7  | 4570  |

As you can see, there's no difference between levels 3 through 5 and 2 is not much slower, so on my system it would make sense to make `low_temp` level 1 instead of level 2. I imagine there is always going to be some variance with hardware so, while I love that zcfan works well out of the box, fine tuning is still desired.

**Comment by cdown** [comment]
Hi there! Glad you find zcfan useful.

While it's possible to allow specifying the level for each temperature, it would certainly make the code more complex, and I'd rather avoid getting into thinkfan territory and keep things as low config as possible. I think that based on what you've identified, the best thing to do is just to change "low" to be set to 1. On my T14s, that gets exactly the same fan speed anyway.

I've just shipped a change to that effect. Thanks! Let me know if that solves your issue and I'll make a new release soon.

**Comment by cdown** [comment]
1.2.0 now out with this change. Thanks!
