### ISSUE TITLE
non-systemd support request

### ISSUE THREAD

**Issue by FrostKnight** [cdown/zcfan#30]
In particular openrc is the one I seek.

I tried one from AUR, but it doesn't work because I cannot start the service

I get this whenever I try to start it:

 * rc-service: No such file or directory

I even have followed the guide here:

https://github.com/MeganerdNL/zcfan-openrc

Would love to have one that works. 

Would you be willing to help me?

**Comment by cdown** [comment]
Running zcfan is as simple as running the binary. Please contact openrc folks if you need support setting it up, I don't use it and so cannot provide support for it.

**Comment by FrostKnight** [comment]
Well okay then, I actually messaged them also.

I assume you have no contributors who use it either... am I right?

Nvm... then. Thanks anyways
