### ISSUE TITLE
zcfan not working on Arch

### ISSUE THREAD

**Issue by Pyntux** [cdown/zcfan#31]
I do not know what can be problem, zcfan is installed from AUR, service enabled and the file:

`/etc/modprobe.d/99-fancontrol.conf`

 is created with:

`options thinkpad_acpi fan_control=1`

**systemctl status zcfan:**

```
systemctl status zcfan.service 
× zcfan.service - Zero-configuration fan control for ThinkPad
     Loaded: loaded (/usr/lib/systemd/system
/zcfan.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Sun 2024-07-28 18:00:29 CEST; 18s ago
   Duration: 29ms
 Invocation: 5929166fecd94d66adb65bf03e0c368f
    Process: 542 ExecStart=/usr/bin/zcfan (code=exited, status=1/FAILURE)
   Main PID: 542 (code=exited, status=1/FAILURE)

Jul 28 18:00:29 T460 systemd[1]: zcfan.service: Scheduled restart job, restart counter is at 5.
Jul 28 18:00:29 T460 systemd[1]: zcfan.service: Start reques
t repeated too quickly.
Jul 28 18:00:29 T460 systemd[1]: zcfan.service: Failed with 
result 'exit-code'.
Jul 28 18:00:29 T460 systemd[1]: Failed to start Zero-configuration fan 
control for ThinkPad.
```

**sudo zcfan:**

```
[CFG] At 90C fan is set to maximum
[CFG] At 80C fan is set to medium
[CFG] At 70C fan is set to low
[ERR] level "full-speed" not supported, using level 7
[ERR] /proc/acpi/ibm/fan: write: Invalid argument (did you enable fan_control=1?)
[ERR] Quitting due to failure during first run
```

P.S. When I put "thinkpad_acpi.fan_control=1" in kernel line of systemd-boot entry, everything works fine. Also everything works fine when manual load thinkpad_acpi module with fan_control=1 and than start zcfan.

**Comment by Pyntux** [comment]
Yes, just put "option thinkpadisa.... " in kernel line of your bootloader...

**Comment by moktavizen** [comment]
You need to [regenerate the initramfs](https://wiki.archlinux.org/title/Regenerate_the_initramfs) to include the .conf file. Try `sudo mkinitcpio -P` on your terminal.

See notes on https://wiki.archlinux.org/title/Kernel_module#Using_files_in_/etc/modprobe.d/

**Comment by Pyntux** [comment]
This is solved :) On Debian you do not need to regenerate...

**Comment by cdown** [comment]
closing, since this is a distro issue, not a zcfan issue. thanks!
