### ISSUE TITLE
Periodic fan spinup on certain Thinkpad models

### ISSUE THREAD

**Issue by Reutertu3** [cdown/zcfan#32]
I'm trying to make the switch to zcfan on my devices and stumbled upon some long forgotten issue that I've also encountered on thinkfan. On certain models the fan will spin up periodically despite the speed being set to 0. Thankfully some clever folks figured it out and submitted a fix (though it has yet to be merged):

https://github.com/vmatare/thinkfan/issues/114#issuecomment-1185230828

Would it be possible to implement the same kind of fix in zcfan?

**Comment by cdown** [comment]
Thanks for reporting! I was not aware of this issue.

I don't have affected hardware, so could you please test #33? :-)

**Comment by Reutertu3** [comment]
Hi!

Thank you so much for your quick response. I just tried it out and indeed
it seems to be working perfectly!

Before (periodic spike):
[image: Screenshot_20241121_154448.png]

After:
[image: Screenshot_20241121_155615.png]

At least on my affected model (E14G4) I can attest that the patch fixes the
issue.

Best regards

**Comment by cdown** [comment]
that's great! i will merge now then. i'll do a release in a few days, too.

**Comment by rodrigoaguilera** [comment]
@cdown I can confirm this works on a thinkpad T495s. Thanks!

A release would be great to avoid compiling once it gets into the repo of the distros

**Comment by cdown** [comment]
1.4.0 released. Thanks!
