### ISSUE TITLE
What are your recommended settings and tools that can be used next to this tool

### ISSUE THREAD

**Issue by CRAG666** [cdown/zcfan#5]
@cdown  I have a Thinkpad P53 and its configuration was a light at the end of the tunnel, since Thinkfan is very coupled, I do super good with this tool but I wonder if you can list or indicate what your configurations they use in your day by day.For example, I don't know if thermald should use or not or if this interfire with Zcfan.I would help me a gia.Thank you very much

**Comment by cdown** [comment]
Hey, I personally don't use any other tools with this. thermald should be somewhat complementary since it cools using non-fan methods, but I just run zcfan with no other thermal daemons. :)
